### PR TITLE
fix pyaudio pkgbuild requirements

### PR DESCRIPTION
**Pull request by AIIX**
- fix pyaudio pkgbuild requirements

### CODE REVIEW

**Comment by JarbasAl** [comment]
the files in these repo are all auto generated, the automations will overwrite your changes on next push, if you want to edit or submit files manually you will need to tweak the automation files

**Comment by AIIX** [comment]
Pypi2pkgbuild is generating wrong pkgbuild files and some packages need to be manually edited to work correctly, some packages also need to be manually added and tweaked with as required for being able to package them and for these to be even usable for packaging

**Comment by JarbasAl** [comment]
> Pypi2pkgbuild is generating wrong pkgbuild files and some packages need to be manually edited to work correctly, some packages also need to be manually added and tweaked with as required for being able to package them and for these to be even usable for packaging

not disagreeing, but the automations are running on every push, need to be changed to only run for specific files and to not overwrite and such, the repo was not set up for receiving PRs and such the classical way, was meant to generate all files

so we need to update automations, every push and PR is triggering a build for every package on PR and on merge....

idk if it overwrites your changes but it might

i would prefer if we could figure out how to make pypi2pkgbuild work correctly for the bad packages

**Comment by AIIX** [comment]
I have disabled the automations on every push for now as I would like to get a full build working with every manual tweak required to get the initial set of pkgbuilds actually building and working with the whole dependency tree satisfied, I already have most of stuff working except a few missing skill dependencies blocking those skills. 

pypi2pkgbuild is not used normally or officially, its just a helper tool for python packages, the pkgbuilds do require lots more manual clean up before I can propose them into distro repo, so I am happy to do the clean up in another branch, if you want to keep this branch for automated pypi2pkgbuild only (not sure how usable those will be), I can build and work against an other proposed branch.

**Pull request merged**
